# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
min_fastlane_version("2.79.0")

default_platform(:ios)

platform :ios do
  before_all do
  	setup_travis
    cocoapods(repo_update: true)
  end

  desc "Capture screenshots and send to iTunes Connect"
  lane :screenshots do
    capture_screenshots
    frame_screenshots
    upload_to_app_store
  end

  desc "Runs all the tests"
  lane :test do
    run_tests(scheme: "BitPrice")
  end

  after_all do |lane|
    notification(
      subtitle: "✅ Lane '#{lane}'",
      message: "Lane '#{lane}' finished with success.",
      sound: "Beep"
    )
  end

  error do |lane, exception|
    notification(
      subtitle: "❌ Lane '#{lane}'",
      message: "#{exception.message}",
      sound: "Sosumi"
    )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
